### ISSUE TITLE
Does not finish install using the pip requirements entry given

### ISSUE THREAD

**Issue by schrinaw** [yourcelf/django-registration-defaults#13]
I installed via pip by copy/pasting the entry given in the README into my requirements.txt.  After pip installs all the entries in requirements, I find that instead of being installed in site-packages, there is just a new folder (in the root of the virtualenv) called src with a folder "django-registration-defaults" and "pip-delete-this-directory.txt".  Seems like the install process is not working as intended.  

EDIT: I should add this is on windows 7.

**Comment by toyg** [comment]
That's actually how it should be: I get the same config and it works fine (but I'm on OSX).

**Comment by yourcelf** [comment]
I've just updated the version on pypi, and changed the README to advise that.  You can install with:

```
pip install django-registration-defaults
```

or add "django-registration-defaults" to your requirements.txt.  The result will be the package installed in your environment's lib/python2.x/site-pakcages/ folder.
