### ISSUE TITLE
pip install is out of date

### ISSUE THREAD

**Issue by jfmatth** [yourcelf/django-registration-defaults#15]
Even though they seem to be the same version, the .3 version that is installed by PIP is just enough different, that django 1.5 won't work on the {% url ... %} tags, it's missing the quotes.

```
(vtest) C:\Users\jmatthew\Development\vtest>pip install django-registration-defaults
Downloading/unpacking django-registration-defaults
  Downloading django-registration-defaults-0.3.tar.gz
  Running setup.py egg_info for package django-registration-defaults

Installing collected packages: django-registration-defaults
  Running setup.py install for django-registration-defaults

Successfully installed django-registration-defaults
Cleaning up...

(vtest) C:\Users\jmatthew\Development\vtest>type Lib\site-packages\registration_defaults\templates\r
egistration\activate.html
{% extends "registration/registration_base.html" %}
{% block title %}{% if account %}Activation complete{% else %}Activation problem{% endif %}{% endblo
ck %}
{% block content %}
{% if account %}
Thanks {{ account }}, activation complete!  You may now <a href='{% url auth_login %}'>login</a> usi
ng the username and password you set at registration.
{% else %}
Oops &ndash; it seems that your activation key is invalid.  Please check the url again.
{% endif %}
{% endblock %}

```

Not sure how to update the pip repository.

**Comment by ccurvey** [comment]
pip install --upgrade -e git+git://github.com/yourcelf/django-registration-defaults#egg=django-registration-defaults

**Comment by jfmatth** [comment]
Hmm, I get that part, but does that upgrade the pypi repo?

Either way, thanks for the package and thanks for the reply.  Love the project

**Comment by ccurvey** [comment]
nope, that does not update PyPI, but it's a workaround that keeps us
moving.  (I ended up in the same place for the same reason.)

On Mon, Sep 2, 2013 at 10:35 AM, John Matthew notifications@github.comwrote:

> Hmm, I get that part, but does that upgrade the pypi repo?
> 
> Either way, thanks for the package and thanks for the reply. Love the
> project
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/yourcelf/django-registration-defaults/issues/15#issuecomment-23663654
> .

## 

The person who says it cannot be done should not interrupt the person who
is doing it.  -- Chinese Proverb

**Comment by yourcelf** [comment]
Thanks -- I've updated the version on pypi.
