### ISSUE TITLE
a few templates don't work with python3.3 and django 1.5

### ISSUE THREAD

**Issue by shevitz** [yourcelf/django-registration-defaults#16]
I am having a problem with 3 templates: activate.html, login.html, and activation_complete.html

I seems that on my setup, python3.3 and django 1.5.1 the urls don't reverse correctly.
The solution I have found moves the {% url  %} tags immediately after the {% block content %} tag. Then everything works fine. Otherwise all links send you back to /login and you can't get past the login screen. 

I think there were 4 changes in all that needed to be made. For whatever reason it seems that the {% url  %} lose scope in the {% block content %} and don't render correctly. 

Thanks,
Danny

**Comment by sorrat** [comment]
Same for me. 
Python 2.7, Django 1.5.1

**Comment by yourcelf** [comment]
Should be fixed in latest master. Thanks!
