### ISSUE TITLE
Where to put base.html?

### ISSUE THREAD

**Issue by nderkach** [yourcelf/django-registration-defaults#18]
Hi,

it's not clear where exactly to put base.html when installing, say with pip into a virtualenv.

Is there a configuration option for Django to specify the path to this template?

**Comment by yourcelf** [comment]
See Django's documentation on the TEMPLATE_DIRS and TEMPLATE_LOADERS settings:

https://docs.djangoproject.com/en/dev/ref/settings/#template-dirs

By default, Django uses the "filesystem loader" and "app directories loader" -- it will look for a folder named "templates" in each app, and in the list of directories specified in TEMPLATE_DIRS.  A file named "base.html" in the root of any of those directories will work (Django will use the first matching file it comes across).
