### ISSUE TITLE
setup.py behavior is inconsistent. 

### ISSUE THREAD

**Issue by usernamenumber** [yourcelf/django-registration-defaults#2]
As written, the "root" variable is set to an empty string when **file**
returns just the filename (no directory component), which is at least the behavior I see running
"sudo python setup.py install" on Fedora 14 using python-2.7-8. 

Replacing **file** with os.path.abspath(**file**) addresses this problem. I will fork and issue a pull request.

**Comment by yourcelf** [comment]
I believe this is fixed, thanks! Closing.
